### ISSUE TITLE
RequireJS Optimizer resolves absolute paths via "baseUrl + paths" rules

### ISSUE THREAD

**Issue by terinjokes** [jrburke/requirejs#1461] opened 2015-12-14 19:41 UTC
The RequireJS docs<sup>[1]</sup> state that modules are resolved via the "baseUrl + paths" rules, with some exceptions:

> There may be times when you do want to reference a script directly and not conform to the "baseUrl + paths" rules for finding it. If a module ID has one of the following characteristics, the ID will not be passed through the "baseUrl + paths" configuration, and just be treated like a regular URL that is relative to the document:
* Ends in ".js".
* Starts with a "/".
* Contains an URL protocol, like "http:" or "https:".

My reading of the Optimizer docs<sup>[2]</sup> suggest that scripts would be resolved per the above docs (in particular, the phrase "just as they are for require.js"):

> For paths and packages, they are relative to baseUrl, just as they are for require.js.

In a project I'm working working on, a config object is passed to `requirejs.optimize` that causes an absolute path (with a ".js" extension) to be resolved. Simplified example:

```javascript
requirejs.optimize({
  include: [ 'modernizr-init' ],
  baseUrl: '/Users/terin/development/Modernizr/lib/../src/'
  rawText: {
    'modernizr-init': 'require(["/User/terin/Development/cf-www/javascript/modernizr/custom-test.js"], function(CustomTest) { /* foobar */ });' }
  }
});
```

Instead of resolving the module to the path "/User/terin/Development/cf-www/javascript/modernizr/custom-test.js", it is resolved by simply prepending `baseUrl`, generating the following error:

```text
Error: ENOENT: no such file or directory, open '/Users/terin/Development/Modernizr/lib/../src//User/terin/Development/cf-www/javascript/modernizr/custom-test.js'
```

The expected behavior is that the RequireJS Optimizer also respects the "baseUrl + paths" exceptions.

Found while resolving https://github.com/Modernizr/Modernizr/issues/1799.

[1]: http://requirejs.org/docs/api.html#jsfiles
[2]: http://requirejs.org/docs/optimization.html#basics

**Comment by jrburke** [comment] 2015-12-16 22:38
On the face of it, looks like a bug, but I am curious why absolute paths are needed in the build environment. With the use of baseUrl in the config, the require([]) could be made relative to that. That could be a workaround for now.

I have not looked into reproducing yet. Putting it in the bucket for next release for more investigation, but happy to have someone try to isolate it more. If the workaround is not feasible and this is blocking Modernizr, I will look sooner into it, but otherwise might not be until later December/early January.

**Comment by terinjokes** [comment] 2015-12-16 23:00
@jrburke I, as a consumer of Modernizr, shouldn't need to know where Modernizr sets as it's baseUrl to and then have the logic to make it relative.

I have a PR open in Modernizr to pass forward absolute paths (the functionality was lost at some point in the past), and could try adding the logic there. But I'd still like to see it fixed here.

**Comment by jrburke** [comment] 2015-12-17 01:58
If it worked in a previous Modernizr 3, does it fail because of an r.js version update? If so, that might help narrow the issue, knowing more details on why if it worked with r.js before why triggered the failure now.

**Comment by terinjokes** [comment] 2015-12-17 02:30
@jrburke I'm just an end user of Modernizr, who hadn't been tracking v3 releases. Adding custom tests was previously supported, but I seemed to have incorrectly implied that absolute paths worked.

Only relative paths from `baseUrl` worked, thought it felt very dirty relying on this behavior. Modernizr, in changing their configuration files, switched from using "test/forms/placeholder" form to just "forms/placeholder" while still using the AMD module id "test/forms/placeholder". They converted the new form to the module id by prepending "test/" to the config value if it wasn't already included. This broke using relative paths as "/Users/terin/development/Modernizr/lib/../src/test/" (`baseUrl` + "test/") isn't a folder.

I added the logic to pass through absolute URLs to custom tests to Modernizr, only to run into this disconnect between documentation in RequireJS.

**Comment by jrburke** [comment] 2015-12-17 05:16
Applied a fix in the r.js repo here:
https://github.com/jrburke/r.js/commit/43733641cb04b6afe941e028893a9a2c1a7f34fa

Snapshot to test latest r.js master is here:
https://raw.githubusercontent.com/jrburke/r.js/master/dist/r.js

I am still a bit unclear on why this issue has surfaced now, and feel like there is a larger issue at play, this may not be the right fix for the original issue, but r.js was definitely not doing the right thing for an absolute path normalization, and that is fixed in master.

However, I am unsure if it is good to use full paths as IDs, generally best to stick with IDs vs paths for all dependency IDs, ultimately more portable, and for build artifacts does not leak an absolute path used on the build machine to a file that could be downloaded to web browsers.

This will be in the 2.1.23 release, but I do not expect to release that until after the winter holidays, likely not until some time in January.

**Closed by jrburke** 2015-12-17 05:16 UTC

**Comment by terinjokes** [comment] 2015-12-17 06:07
> but r.js was definitely not doing the right thing for an absolute path normalization, and that is fixed in master.

Thank you.

> However, I am unsure if it is good to use full paths as IDs, generally best to stick with IDs vs paths for all dependency IDs, ultimately more portable, and for build artifacts does not leak an absolute path used on the build machine to a file that could be downloaded to web browsers.

This is likely true, and sometimes we need to step back from using the hammer to investigate if we're even working with a nail.

In light of your comments here, I'll investigate modifying my patch to Modernizr to allow for relative paths, and also look into seeing if `paths` configs can be merged with the Modernizr defaults to allow for module ids on custom tests that don't require the absolute path.
