### ISSUE TITLE
Load timeout of module: main.js

### ISSUE THREAD

**Issue by Ashok-ss** [jrburke/requirejs#1462] opened 2015-12-18 07:15 UTC
Hi, I am getting the following error : Load timeout of module: main.js

My rconfig looks like this:

require.config
  shim:
    Ember:
      deps: ['jQuery']
      exports: 'Ember'

    breeze:
      deps: ['Q', 'Pluralize']
      exports: 'breeze'

    Q:
      deps: []
      exports: 'Q'

    bootstrap:
      deps: ['jQuery']
      exports: 'bootstrap'

    Slick:
      deps: ['jQuery']
      exports: 'Slick'

    slickGrid:
      deps: ['Slick']
      exports: 'slickGrid'

    notify:
      deps: ['jQuery']
      exports: 'notify'

    jqueryEventDrag:
      deps: ['jQuery']
      exports: 'jqueryEventDrag'

    "bootstrap-dialog":
      deps:['jQuery','bootstrap']
      exports:'bootstrap-dialog'

  map:
    '*':
      "IPv6": "false"
      "punycode": "false"
      "SecondLevelDomains": "false"

  paths:
    lodash: 'lib/lodash'
    Ember: 'lib/ember'
    jQuery: 'lib/jQuery'
    jQueryUI: 'lib/jquery-ui'
    DateTimePicker: 'lib/bootstrap-datetimepicker'
    bootstrap: 'lib/bootstrap'
    "bootstrap-dialog":'lib/bootstrap-dialog'
    MultiSelect: 'lib/bootstrap-multiselect'
    modernizer: 'lib/modernizer'
    EmberTemplateCompiler: 'lib/ember-template-compiler'
    breeze: 'lib/breeze'
    BreezeMetaHelper: 'lib/breeze-helper'
    breezeRestDataService: 'lib/breeze-rest-dataservice'
    Q: 'lib/q'
    uri: 'lib/uri'
    jqueryEventDrag: 'lib/jquery.event.drag'
    Slick: 'lib/slick.core' 
    slickGrid: 'lib/slick.grid'
    gridRowSelection: 'lib/grid.rowselectionmodel'
    gridCheckboxSelection: 'lib/grid.checkboxselectionmodel'
    gridAutoToolTips: 'lib/grid.autotooltips' 
    moment: 'lib/moment'
    momentRange: 'lib/moment-range'
    BreezeRestUriBuilder: 'breezeRestUriBuilder'
    notify: 'lib/notify'
    "false": 'lib/false'
    Pluralize: 'lib/pluralize'
    handlebarsRuntime: 'lib/handlebars.runtime'
    socketIO: 'lib/socket.io'
    accounting: 'lib/accounting'
    logger : 'lib/logger'
    Cookie : 'lib/js.cookie'
    Sugar  : 'lib/sugar-full'

Any my main.js looks like this

define [
  "rconfig"
  ], (Config) ->
    
    startup = ->
      require ['Ember', 'Apollo', 'Q', 'common/constants'], (Ember, Apollo, Q, C) ->
        window.Q = Q
        window.C = C
        require [ 'router', 'models/index', 'models/gridLoaders/event'], (Router, Models, eventGridLoader) ->

          Apollo.Router.map Router

          Apollo.ApplicationRoute = Ember.Route.extend
            model: ->
              promise = authManager.authenticate()
              promise.then ->
                configPromise = AppConfig.getConfig()
                configPromise.then (data)->
                  window.logger.customLogLevel data.logLevel
                configPromise

             enteringRoute: (->
              @timeHandles = new serverTime()
              @timeHandles.get()
             ).on('activate')

             exitingRoute: (->
              @timeHandles.clearIntervals()
             ).on('deactivate')

    startup()

I have made sure there is no error in the required modules in main.js.

I tried to give waitSeconds: 0 in my config, but it does not consider that rather it takes a default timeout of 7 seconds and timesout

Kindly suggest any help. Thanks.

**Comment by chrisknoll** [comment] 2015-12-18 22:18
I think you get this type of timeout error when you attempt to load the same moduleID from different resources. Can you check that?

**Comment by amenadiel** [comment] 2015-12-18 23:40
I don't use Ember, but I believe your problem might come from the framework or another library requiring `jquery` as a named module, so you should use lowercare when declaring its path in the config, and do the same wherever you list it as a dependency.

Also, you shouldn't have shims for libraries that support AMD. Properly encapsuled libraries won't expose their main object to the global namespace, so the shim won't have access to its supposed export value.

**Comment by jrburke** [comment] 2015-12-19 18:29
Closing as a discussion ticket, not a bug fix ticket for requirejs. Feel free to continue discussion here though.

**Closed by jrburke** 2015-12-19 18:29 UTC

**Comment by Ashok-ss** [comment] 2015-12-21 10:00
@jrburke @amenadiel @chrisknoll I am trying to set waitSeconds: 200 in my config. But its not getting picking up from my config file rather it takes a default value. I am using requirejs version 2.1.22. Any idea how to solve this please?

**Comment by luqin** [comment] 2016-01-04 08:40
Same error +1. Error when size 6.4m

**Comment by jrburke** [comment] 2016-01-21 04:25
As long as the file with the waitSeconds config is loaded, or is at the top of the file, it should take effect. If `<script data-main=""...` is used, and the data-main script is the thing timing out, then do not use data-main, but instead just have the script tag for require.js followed by a `<script>requirejs.config({waitSeconds: 200}); require([...]);</script>` call.

If you want to turn off the waitSeconds timer completely, [set it to 0](http://requirejs.org/docs/api.html#config-waitSeconds).
