### ISSUE TITLE
How to make two requireJS project work in different contexts.

### ISSUE THREAD

**Issue by Pubbledev** [jrburke/requirejs#1242] opened 2014-11-24 09:55 UTC
I'm having a bit of trouble with contexts in requireJS. We have two JS project based on requireJS and backbone. they would work perfect if work on their own page. But their context conflict each others if I put them into same page.

Both projects follow similar module name convention.

Project A:

Main.js:

require.config({
    baseUrl : "javascript/app1/",
    waitSeconds : 20,
    paths : {
        jQueryPB : "jquery-1.10.1.min",
        underscore : "underscore",
        backbone : "backbone-min",

    },
    shim : {
        underscore : {
            exports : "_"
        },
        backbone : {
            deps : [ "underscore", "jQueryPB" ],
            exports : "Backbone"
        }
    }
});

require([ "app" ], function(app) {

   app.startup();

});

App.js

define([ "jQueryPB", "backbone", "underscore", "models/app", "views/app" ], function($jpb,
        Backbone, _, appModel, appView) {

    var appInfo = new appModel();
    var app = new appView({
        model : appInfo
    });

    return app;
});

views/app.js

define(
    ["jQueryPB", "backbone", "views/moduleB"], function($jpb, Backbone, moduleB) {
        var appview = Backbone.View.extend({

....

views/moduleB

In the moduleB, I need to access some properties of app instance (Project A). so I use var app = require("app");

Project B:

The project B has very similar module structure as Project A. I only renamed app.js to appb. There is a moduleC also need to access properties of app instance (Project B)

var appb = require("appB")

I got following error when I access them from host html page:

Uncaught Error: Module name "app" has not been loaded yet for context: _. Use require([])

OR error on loading project B sometimes:

Uncaught Error: Module name "appB" has not been loaded yet for context: _. Use require([])

It looks like that they are trying to load module from each other's context or global context, but only one app instance is stored in there.

How could I set modules to live in its own project context?

Thanks

**Comment by Virbhadrasinh** [comment] 2015-01-23 15:19
https://github.com/jrburke/requirejs/issues/1042#issuecomment-71207497

**Comment by jrburke** [comment] 2015-01-23 19:43
The other ticket mentioned may help, but sounds in general like [Multiversion/multiple context support](http://requirejs.org/docs/api.html#multiversion). Closing as a discussion ticket, not a bug fix ticket.

**Closed by jrburke** 2015-01-23 19:43 UTC
