### ISSUE TITLE
Cannot load module with "module" as name

### ISSUE THREAD

**Issue by imatmati** [jrburke/requirejs#1448] opened 2015-11-13 20:25 UTC
Hi,

I defined some module for an angularjs application. It happened that I named 'module' the module responsible for bringing the angular module.

If I configure my file module.js to be represented by the path 'module' 

### app.js
`requirejs.config({

    baseUrl: '../js/bower_components',
    paths: {"angularjs" : "angular/angular",
            "module" : "../module",
            "controllers" : "../controllers",
            "directives": "../directives"
    }
});`

### module.js
`define (["angularjs"], function() {

    return  angular.module("app",[]);
})`

'module' is never found as a dependency in any other definition of module where it's required like there :
### directive.js
`define(["angularjs","module"], function(_, app) {

    app.directive("alert", function() {
        return {
            template: "<div class='alert'>{{msg}}</div",
            restricted: 'E'
        };
    })
});`

But if I rename the path module to "mod" for instance, and that I correct the name in every requirement of modules, it works.
It appears that the name "module" can't be used as a path name. Too bad, because it's very usable.
Have a nice day.

**Comment by jrburke** [comment] 2015-11-16 05:49
Right, this is a restriction due to wanting to interop with CommonJS style modules, [More details here](https://github.com/jrburke/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define#magic). Closing as this is working by design.

**Closed by jrburke** 2015-11-16 05:49 UTC
