### ISSUE TITLE
Shim not respecting dependency

### ISSUE THREAD

**Issue by isuftin** [jrburke/requirejs#1400] opened 2015-08-09 15:28 UTC
I am attempting to use RequireJS to load a AMD-capable mapping library and a non-AMD plugin for that library.

The AMD-capable library is loaded properly and I am able to use it in my modules. However, the non-AMD library that I set up a shim for seems to not be able to be loaded. It expects there to be a global "ol" variable and that's how I set up the shim for it but when I try to load it, the plugin complains that "ol" is undefined.

This is the very simple implementation I've boiled it down to, and I can't see what I'm doing incorrectly.

Is it me? 

index.html:
```

<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
    <script data-main="init" src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.20/require.js"></script>
</body>
</html>
```
init.js:
```
require.config({
        paths: {
                'ol': ['//cdnjs.cloudflare.com/ajax/libs/ol3/3.7.0/ol'],
                'olLayerSwitcher': ['//cdn.rawgit.com/walkermatt/ol3-layerswitcher/v1.0.2/src/ol3-layerswitcher']
        },
        deps: ['main'],
        shim: {
            'olLayerSwitcher':  ["ol"]
        }
});
```

main.js:
```
define(['ol', 'olLayerSwitcher'], function (ol) {
    // Coming into this module, I am seeing ol3-layerswitcher.js:9 Uncaught ReferenceError: ol is not defined
    // That code looks like: 
    // ol.control.LayerSwitcher = function(opt_options) { ... }
});
```

**Comment by amenadiel** [comment] 2015-08-10 00:12
Each shim should containing deps and optionally exports key

```js
require.config({
        paths: {
                'ol': ['//cdnjs.cloudflare.com/ajax/libs/ol3/3.7.0/ol'],
                'olLayerSwitcher': ['//cdn.rawgit.com/walkermatt/ol3-layerswitcher/v1.0.2/src/ol3-layerswitcher']
        },
        shim: {
            'olLayerSwitcher': {
                "deps": ["ol"]
            }
        }
});
```

**Comment by isuftin** [comment] 2015-08-10 12:24
@amenadiel I am trying it your way as well and I am still seeing the same issue. In my project I am actually loading the files from my local file system but I wrote this simple setup above using the CDN because it allows you or others trying to diagnose the issue to easily recreate the issue on your machine as well.

What's strange about this is that this setup (my original and yours) works fine in a Java project I am writing. However, when I tried to run Jasmine tests against the same configuration, when Jasmine loads up the modules that use that third party OpenLayers3 plugin, I start seeing the issue. I struggled with it for a while and boiled it down to the issue above.

**Comment by davidmsibley** [comment] 2015-08-10 20:17
it seems like this is about layerswitcher needing a global dependency.  One solution to this is changing init.js to 
```
require.config({
        paths: {
                'ol': ['//cdnjs.cloudflare.com/ajax/libs/ol3/3.7.0/ol'],
                'olLayerSwitcher': ['//cdn.rawgit.com/walkermatt/ol3-layerswitcher/v1.0.2/src/ol3-layerswitcher']
        },
        deps: ['main'],
        shim: {
            'olLayerSwitcher':  {
              deps: ["olshim"]
            }
        }
});
```

and adding in a olshim.js module to your project:
```
define(['ol'], function (ol) {
  window.ol = ol;
});
```

this is poluting the global namespace, but other than editing layerswitcher to be an actual amd module, you might be stuck to that

**Comment by isuftin** [comment] 2015-08-11 11:52
@davidmsibley This works and I may end up using this pattern. However, I wish that the RequireJS documentation reflected this issue and it doesn't seem to. I was under the impression that this is specifically what the shim configuration is for.

**Comment by jrburke** [comment] 2015-08-20 19:14
The issue is that ol.js does not export a global if there is an AMD loader:

```
(function (root, factory) {
  if (typeof exports === "object") {
    module.exports = factory();
  } else if (typeof define === "function" && define.amd) {
    define([], factory);
  } else {
    root.ol = factory();
  }
}(this, function () {
```

This UMD registration block is great because it plays well with a module system. 

However shim config is only meant for things that do not register with a module system, and it only works if the dependencies of shims are also not module system aware. There is a note about this caveat in the [shim docs section](http://requirejs.org/docs/api.html#config-shim) but it is at the very bottom and worded in with other disclaimers and easy to miss, particularly since it requires knowing the internal structure of the dependencies in play.

Closing as an expected side effect, but I can see how it is frustrating to discover this. Thanks to @davidmsibley for uncovering the root issue.

**Closed by jrburke** 2015-08-20 19:14 UTC
