### ISSUE TITLE
Managing dependancies in cross domain application architecture 

### ISSUE THREAD

**Issue by mildfuzz** [jrburke/requirejs#1295] opened 2015-03-04 10:02 UTC
I am using requireJS to asynchronously load applications from remote servers.

The issue I am having is requirejs baseUrl is static to the initial require load, on my host domain, and this causes 404's when remote application load their dependancies. 

At the moment I am having to pass Urls as arguments into modules to change the baseUrl in order to have the dependancy for that module resolve correctly, but this feels horribly hacky.

Is there a better way to allow modules to be aware of their own location and load dependancies based on that in a cross domain architecture or is requireJS just the wrong tool for the job?

**Comment by jrburke** [comment] 2015-03-04 17:57
The paths config can help point module ID prefixes to other domains, so that is the recommended way to deal with that, and to make sure the remote stuff is all under a module ID prefix, and if they use relative IDs inside that ID space to refer to each other, it should work out. So if 'remote1' is pointing to the remote location, and say there is a 'remote1/app' module that refers to a 'remote1/helper', the app module could refer to it via the './helper' relative ID.

Those are the tools that are available though. Depending on the setup, the packages and map [config options](http://requirejs.org/docs/api.html#config) might also be useful too.

Closing as a discussion ticket, not a bug fix ticket. Feel free to continue discussion here.

**Closed by jrburke** 2015-03-04 17:57 UTC

**Comment by mildfuzz** [comment] 2015-03-05 08:58
I might be misunderstanding your suggestion, but the issue for me here is that we then have to explicitly state each path, which reduces our flexibility of moving from int, stage and production environments. 

What would be better for us is the idea that each files dependancies, unless listed in the path object, are derived as relative to that file (or absolute, if an absolute path is given). I am not sure if this is even possible, let alone a candidate for a feature request.
