### ISSUE TITLE
RequireJS doesn't evaluate modules in correct order

### ISSUE THREAD

**Issue by pilaas** [jrburke/requirejs#1409] opened 2015-08-19 19:39 UTC
I have following file structure:

- jquery.js
- index.html
```
...
<script>
  require(["app"], function() {
    console.log("App started");
  });
</script>
...
```
- app.js
```
define(["a1", "b1", "c1"], function() {
    console.log("Main module loaded.");
});
```
- a1.js
```
define(["jquery"], function() {
    console.log("a1 loaded");
});
```
- b1.js
```
define(function() {
    console.log("b1 loaded");
});
```
- c1.js
```
define(function() {
    console.log("c1 loaded");
});
```

Documentation says that *The RequireJS syntax for modules allows them to be loaded as fast as possible, even out of order, but **evaluated in the correct dependency order**, and since global variables are not created, it makes it possible to load multiple versions of a module in a page.*.

As I understand, the result of running this *app* should be:
```
a1 loaded
b1 loaded
c1 loaded
Main module loaded.
App started
```

Unfortunately, the result is:
```
b1 loaded
c1 loaded
a1 loaded // loads at the end because of jquery.js dependency 
Main module loaded.
App started
```

Do I misunderstand the documentation?

**Comment by jrburke** [comment] 2015-08-19 20:57
The result is an expected result: there is no guarantee that app.js asking for dependencies ["a1", "b1", "c1"] will result in those scripts executing in that order. For instance, what if "a1" depended on "c1". If a script loads and it does not have any dependencies, then the loader will execute the define() factory function as soon as it can, it does not track for example that "a1" was listed before "b1" in the app dependencies, because other modules could have also listed those dependencies in a different order.

The loader only cares about delaying a define() factory function execution if it has dependencies, otherwise it is considered fair game to execute the define() factory function as soon as the loader prefers.

The dependencies are only there to express the dependency tree relationship, it does not imply a sequential ordering like HTML script tag ordering does.

Closing as discussion ticket, not a bug fix ticket, but feel free to continue discussion here.

**Closed by jrburke** 2015-08-19 20:57 UTC
